### ISSUE TITLE
Build timeout

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#114]
The build is currently failing with a time-out on the running of the Norne FlowNet setup.

**Comment by anders-kiaer** [comment]
Scheduled CI has indeed failed two nights in a row (https://github.com/equinor/flownet/actions?query=event%3Aschedule). What is strange is that the third last scheduled CI finished successfully, and that is the same commit hash of master as the two that have failed. Also, 3.6 were successfull in both failed run (3.7 timed out).

Interesting to see tomorrow if the trend continues.

**Comment by anders-kiaer** [comment]
My best guess here is that the dependencies `libres` / `ert` still are a bit fragile in terms of killing realizations taking a long time.  `flownet` (through it's user configuration file) could maybe have an optional configuration setting "total time to spend", useful in debug/CI contexts, which is then passed on to `run` as `timeout` (https://docs.python.org/3/library/subprocess.html#subprocess.run). On `TimeoutExpired` we can then do some automatic debug checks of the ert run, which would help in CI settings. (We already have something on this, but that applies to settings where all realizations fails - not ert hanging forever and never finishes).

**Comment by olelod** [comment]
Seems like the build is passing again today

**Comment by wouterjdb** [comment]
> My best guess here is that the dependencies `libres` / `ert` are a bit fragile in terms of killing realizations taking a long time (or detecting that they have finished).
> 
> `flownet` (through it's user configuration file) could maybe have an optional configuration setting "total time to spend", useful in debug/CI contexts, which is then passed on to `run` as `timeout` (https://docs.python.org/3/library/subprocess.html#subprocess.run). On `TimeoutExpired` we can then do some automatic debug checks of the ert run (check useful files on "scratch" - was something really hanging, and if so on which job etc.), which would help in CI settings. (We already have something on this, but that applies to settings where all realizations fails - not ert hanging forever and never finishes).

👍

**Comment by anders-kiaer** [comment]
Closed by #119.
