### ISSUE TITLE
High degrees of freedom with individual satnum/eqlnum

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#139]
When simulating Norne, there are clearly different equilibration regions. Also tuning the relative permeability individually will be beneficial for a well-by-well match. However, when options are set to individual, without adding a single additional node, the degrees of freedom end up at nearly 30,000, which is about 4 times the number of 'observations'.

We should consider limiting the number of equilibration/relative permeability regions to have the right amount of flexibility. A simple first step could be to take the original simulation regions and assign the same regions number in the same locations.

This would in essence not violate the data-driven principle of FlowNet as we could assign regions based on well properties. But before answering that question, testing the principle based on simulation model output could be useful.

**Comment by olelod** [comment]
In theory flow tubes can be completely outside of the original simulation grid. Any thoughts on what to assign then? Find the closes tube which has allready been assigned to a region and use that one? Other suggestions?

**Comment by wouterjdb** [comment]
Yes, the nearest region. But nearest tube is (nearly) the same.

**Comment by olelod** [comment]
Slowly getting there
<img width="572" alt="norne_ecl" src="https://user-images.githubusercontent.com/46521401/92334066-c933f500-f08a-11ea-8ff9-02841493da92.PNG">
<img width="631" alt="flownet" src="https://user-images.githubusercontent.com/46521401/92334067-c9cc8b80-f08a-11ea-9ef5-256075261307.PNG">

**Comment by olelod** [comment]
For EQLNUM i clearly see the need for being able to define values for individual regions in the config yaml. Do we want the same for SATNUM? Is it enough to be able to change parameters per region, starting out with the same values?
