### ISSUE TITLE
Test: Include log data into FlowNet

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#154]
Including log data to improve priors has been something we wanted to test out for a long time. Now that we are working with Norne we see that an improved prior might be needed.

It is therefore suggested to test out including log information (permeability and porosity) to steer the prior distributions of the FlowNet for these quantities.

A possible implementation would be to (from the simulation model as input) calculate the (harmonic?) mean permeability along the connections and assign an uncertainty. Then, assign distributions to all connections based on nearby measured values.

The following image is an attempt to visualize the envisioned methodology:

![image](https://user-images.githubusercontent.com/9119793/91538464-2b1c8e00-e918-11ea-9af1-049cc361478f.png)

Any input @olelod @anders-kiaer @olwijn @edubarrosTNO @tayloris?

**Comment by wouterjdb** [comment]
@edubarrosTNO suggested to use kriging.

I google for a few seconds and found https://github.com/GeoStat-Framework/PyKrige; could that be something? (3D supported)

**Comment by edubarrosTNO** [comment]
Agree on the approach. Even if we start simple this will give us some insight on the usefulness of these "constraints" for the prior.

First step is to fetch the permeability values from the connections in the reference simulation model (let me know if you need to discuss, I have done this before using `libecl`). We should be careful with the averaging though. It will be simple for the Egg model which is basically a 2,5D model (layers look very similar), but things might become more tricky if there are connections in different formations.
Second step: "interpolation" between measured values. Kriging as you mentioned might become useful.

Finally, I think this task also links to the older #38 issue.
