### ISSUE TITLE
Deepest point perforation strategy failing on D-4H well in Norne model

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#156]
The connection of the wells to the flownet have so far often been simplified by using the deepest point of the well. However, in the Norne model the D-4H is very deep which means that in FlowNet the connection is always far below the oil-water contact (see red circle). In the simulation model D-4H is a very good producer, from the shallower perforation, whereas in FlowNet D-4H can only produce water (and lots of it).

![image](https://user-images.githubusercontent.com/9119793/91719826-45fc3600-eb96-11ea-901c-24194d799b76.png)

The connection strategy should be reconsidered.

There are many variants possible, the shallowest, the deepest opened connection at any given time, the perforation with the highest PI, etc, etc.

None of them are perfect. I suggest not to find the "best" strategy, but find a more robust strategy.

For example:
**The time-weighted average open connection location/depth during the observed production life of the well.** This would lead in the D-4H case to the connection being roughly at the purple circle.

**Comment by wouterjdb** [comment]
✔️ Checked connection location (yellow crosses)
![image](https://user-images.githubusercontent.com/9119793/91807021-6d9ddd80-ec2c-11ea-98c7-52798ab9be25.png)

**Comment by tayloris** [comment]
An alternative strategy would be to study the time of flight around the well from a given velocity field from the simulation. And then we can choose the location with a higher flow. This will require extra calculations that should not require high computational costs.
