### ISSUE TITLE
More attention to network in the vertical plane

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#202]
In the open Norne case we see WAG injection at lower layers, with horizontal producers at the top layers. In the previous cases we were dealing primarily with vertical wells, so we had a strong focus on designing a nice network to capture horizontal flows (good distribution of "imaginary" nodes in the horizontal plane). We should start paying more attention to the placement of "imaginary" nodes in the vertical plane to capture more complex behavior (e.g. gas gravity-driven flows, more fluid contacts)

**Comment by wouterjdb** [comment]
This is now being worked on via #255. Closing this issue.
