### ISSUE TITLE
Pyscal interpolation option causing large number of failing simulations

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#209]
I noticed that when using the `interpolate: true` entry in `relative_permeability`, a lot more simulations fail already with the prior ensemble as set up for the Norne case (current version on `flownet-testdata / master`). I also observed that the simulations take much longer to run when `interpolate: true` compared to `interpolate: false`

**Comment by olelod** [comment]
Do we have a simple way of plotting/comparing the relative permeability curves produced by either method for some flow tubes? A number close to -1 will in practice use low values for all the relative permeability parameters, and a number close to 1 will use all high values. Maybe the curves are getting "numerically difficult" due to that? When we are not interpolating, the different values are drawn independently, so we are maybe  not end up in a very pessimistic or very optimistic scenario?

**Comment by wouterjdb** [comment]
You could potentially test with running pyscal in normal mode and not "fast mode" - that should spotted (obvious) errors.

**Comment by olelod** [comment]
I don't think the functionality around interpolating between low/base/high has a fast model implemented. I could not find a way to pass along the fast parameter, at least.

**Comment by wouterjdb** [comment]
> I don't think the functionality around interpolating between low/base/high has a fast mode implemented. I could not find a way to pass along the fast parameter, at least.

Ok, then that doesn't help.

**Comment by olelod** [comment]
I have been cheking a little and thinking a bit. So, as of now, the most pessimistic relperm curve is made up from all the low input values, but come to think of it, some low values are actually good for us.... This makes the initial ensemble look quite weird in the interpolation case: ![image](https://user-images.githubusercontent.com/46521401/98228017-55ae4700-1f58-11eb-9df2-8cba1824bb2e.png)

Generating curves without interpolation gives an ensemble like this:
![image](https://user-images.githubusercontent.com/46521401/98228454-e5ec8c00-1f58-11eb-9ec1-916ddcd922ae.png)

**Comment by olelod** [comment]
#231 will hopefully help here

**Comment by olelod** [comment]
#231 has been merged so hopefully you will see improved performance now @edubarrosTNO

**Comment by wouterjdb** [comment]
@edubarrosTNO will test today.
