### ISSUE TITLE
Negative porosity when using mean and max in the config

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#210]
Setting porosity with a mean and max will lead to realizations with negative porosity and failed runs:

![image](https://user-images.githubusercontent.com/9119793/95591914-3949e800-0a48-11eb-8ed9-2d6a3a728911.png)

![image](https://user-images.githubusercontent.com/9119793/95591903-351dca80-0a48-11eb-8fb9-54098cab4bcc.png)

This is always invalid and should lead to a crash.

**Comment by olelod** [comment]
Should we move part of what is done in `_run_ahm.py` into the config parsing, such that this is discovered earlier? Raise an error there if what you define would lead to negative min.

**Comment by wouterjdb** [comment]
Yes, sounds good. However, another thing is that the code that calculate the distributions is very slow. So still it would take some time to get the error. I guess we can do this faster.

**Comment by olelod** [comment]
For the uniform distribution it should be pretty straightforward. The loguniform one is a different beast i guess. I guess it has a use case when a parameter has a lower bound you can not theoretically pass (such as 0 porv or poro), but if you define the mean and max, you can end up with e.g. a minimum porosity of 0.15. What we are really saying then is that the lowest possible (and most likely) value of porosity is 0.15. I don't think this is what we really want - we want some other distribution that moves towards lower probability in the prior as we move towards the boundaries (but that is more fundamental than what this issue aims at...)

**Comment by olelod** [comment]
PR #251 adds multiple checks on the input values, which should close this issue.
