### ISSUE TITLE
Additional summary vectors for the Norne case

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#211]
To gain understanding on the matching of Norne, it would be useful to add a few more summary vectors in the reference Eclipse and FlowNet simulations. A few vectors would be:
- FLPT, FLPR (to track liquid production)
- FVPT, FVPR (reservoir volume production)
- FPR (average reservoir pressure)
- FMWPR (number of open producers)
- FMWIN (number of open injectors)
- WMCON (number of open well connections)

To be checked: if OPM-Flow supports all of these.

**Comment by wouterjdb** [comment]
`WMCON` is **not supported** at the time of writing.

The rest is supported.

You probably also want the historic vectors on the field scale for easy comparison.
