### ISSUE TITLE
Enable HM controls in the FlowNet config file 

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#219]
It could be useful to enable HM controls / targets for producers (WCONHIST) and injectors (WCONINJH) to be set in the FlowNet config file. Right now, the target 'RESV' is set for producers (where a few other options would be possible) and 'RATE' for injectors (where it could be also 'BHP').

**Comment by olelod** [comment]
By using `WHISTCTL` we can potentially provide a list of dates and control modes in the config yaml. It should override the control mode given in `WCONHIST`.
