### ISSUE TITLE
No shutting in of wells in the Flownet (history) schedule

### ISSUE THREAD

**Issue by olwijn** [equinor/flownet#22]
Production wells operating under an economic constraint may be shut in at e.g. high WCT. In the Flownet schedule file production wells are currently not explicitly shut in but simply disappear from the history schedule (i.e. no new WCONHIST entries appear after the shut-in date). This results in the well remaining open with the last assigned operating target. Shutting in of the well could be achieved by adding e.g. the schedule entry

WCONHIST
  'BR-P-18' 'SHUT' 'RESV' /
/

at the correct shut-in time. It was verified that this has the desired effect.

It is not clear if the well status can be extracted from OPM Flow output as read by ERT. An alternative may be to implement a rule that says, for example, that if liquid rate and BHP are both 0 this means that the well is shut-in.

**Comment by anders-kiaer** [comment]
Agree, this should be fixed. Might perhaps be scenarios where adding `'SHUT'` (complete isolation from formation) at the last time step is not preferred, and `'STOP'`(well stopped above formation) is better. Would be nice if we can differentiate between the two in FlowNet.

I looked into the The Manual, and there is a vector called `WSTAT` which perhaps can be used. Its value indicates the well state.
- 0: Producer
- 1: Injector
- 2: SHUT
- 4: STOP
- 5: PSHUT 
- 6: PSTOP
