### ISSUE TITLE
Network generation for Egg model

### ISSUE THREAD

**Issue by tayloris** [equinor/flownet#24]
This figures shows the network generated by Flownet for the Egg reservoir model.

![Flownet_network_for_EggModel](https://user-images.githubusercontent.com/28102851/80082953-569c0000-8555-11ea-8531-e515bbad5c02.png)

Aditional to the connections Injector - Producer, you will connections producer-producer and also connections Injector - Injectors. I understand these connections are generated by default. However, there are connections that should no be there (in my opinion). There is a connection, for example, the one between injector 2 and injector 6 that i don't understand. Both wells are far away from each other. 

It would be interesting to include in the configuration file an option to influence the creation of the network in flownet.

**Comment by wouterjdb** [comment]
This is the result of the connection being generated in 3D. It looks like the path cross one another but in fact they are above/below each other.  I agree with you that it would be nice to have more flexibility in how the network is generated. I'm not sure at this point how though. Suggestions? Maybe ignoring a path that is less than x meters above/below another path if it is shorter?

However, I do not _in general_ agree with the assumption that, based on two wells being far away, they should not be connected to one another directly. It might be less likely that they have a direct communication path, but it is the geology that dictates whether or not this is the case. We do not know that a priori and, letting the assisted history match figuring out whether or not a direct communicating path is needed, seems to be the more data-driven approach in my opinion.

**Comment by wouterjdb** [comment]
As a result of #128 we now have the possibility of setting the maximum length of a connection. Maybe that is a potential solution for this problem as well?
