### ISSUE TITLE
Use cumulative production as observations

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#266]
Currently we see that the cumulative production is always off. Could it help steering the model in the right direction by condition the model to cumulative "observations" as well?

**Comment by olwijn** [comment]
Cumulative rates (Eclipse keywords WOPT, WWPT and WGPT) were added as possible observation types. A first test using only WOPT data at the final time with a 10% relative error standard deviation suggests that this might help to move the ensemble in the right direction, perhaps as a first step that could be followed by further fine tuning.
![image](https://user-images.githubusercontent.com/13539085/101149447-3cfc8400-361f-11eb-95d6-8de2348b8c37.png)
