### ISSUE TITLE
High memory usage when running individual relperm scheme on norne

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#278]
The memory usage for the individual relperm scheme is very high. When running on the flownetsimulator VM with 70 cores I'm using more than 140GB of memory during the process of building the FlowNet realization. This does not happen when the relative permeability model is set to global.

Do we have a memory leak?

**Comment by wouterjdb** [comment]
Tested and it is actually the fact when the relative permeabilities are created we are spawning a lot of new processes due to the usage of the processpoolexecutor. On the flownetsimulator, with 70 cores, we already have 70 process running started by ert, which are then mutliplied by 70 again, with full duplication of process memory.
https://github.com/equinor/flownet/blob/d81a3833a742a95bff96c7c487a66cd739b20b97/src/flownet/parameters/_relative_permeability.py#L296-L319

**Comment by olelod** [comment]
Below is an example with two iterations, ten realizations (where max running is set to five). The figures show a comparison of memory usage when using ProcessPoolExecutor compared to ThreadPoolExecutor when rendering the individual relative permeability tables in parallel for the different realizations. With ProcessPoolExecutor we see distinct spikes in the memory usage when we render the realizations (more specifically when we write the SWOF and SGOF to disk). When using ThreadPoolExecutor, the rendering takes more time, but uses less memory.
![ThreadPoolExecutor](https://user-images.githubusercontent.com/46521401/107806936-c4751a80-6d67-11eb-8fb5-8e124d989bcd.JPG)
![ProcessPoolExecutor](https://user-images.githubusercontent.com/46521401/107806941-c50db100-6d67-11eb-9629-0f2b918eaab6.JPG)
