### ISSUE TITLE
Relative permeability interpolation option runs slow and with warnings

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#286]
When running with the interpolation mode (and "individual" relative permeability scheme) I'm getting a lot of warnings:

![image](https://user-images.githubusercontent.com/9119793/101766789-93683780-3ae3-11eb-9d26-bf3a21f0656f.png)

Also, the model is actually not finished creating before ERT kills the realization as it has been running until the maximum simulation time. Of course increasing that time could help, but the underlying problem is that the generation of the relative permeability curves takes too much time for the individual relative permeability scheme using interpolation.

Any thoughts @olelod @edubarrosTNO?

**Comment by olelod** [comment]
There is no fast option available for SCALrecommendation (the interpolation between curves) in pyscal as of yet. Also there is currently no parallelization implemented for the interpolation option in FlowNet - that may speed things up a little bit.
