### ISSUE TITLE
Installation problem, ecl>=2.9 and flow path

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#289]
- I am having troubles in installing **flownet**. In particular, after running

 `pip3 install flownet`

I got: _Could not find a version that satisfies the requirement ecl>=2.9_
 The requirement ecl>=2.9 is not satisfied. Indeed, if I try to manually install ecl with `pip3 install ecl`, the only available version is 0.0.0

- If I try to install **flownet** cloning the github repo, after running 

`pip3 install -e .`
and replacing the `ecl>=2.9` in the setup.py file with `ecl`, pip cannot locate the flow installation path, even if it is` /usr/bin/flow` and even correctly defining `FLOW_PATH`. Note that I have installed the last version `flow 2020.10`

Any suggestion?
Thank you

**Comment by wouterjdb** [comment]
My first thought would be to try to update pip on your venv/machine:

`pip install --upgrade pip`

And then try again. Any luck?

**Comment by Riccardopeli** [comment]
Thank you!
That was the point.
The flownet  installation via pip succeeded !

**Comment by wouterjdb** [comment]
👍
