### ISSUE TITLE
Default probability distributions

### ISSUE THREAD

**Issue by olelod** [equinor/flownet#291]
In PR #251 all default probability distributions are set to `uniform`. Maybe some parameters should have a different default?

**Comment by wouterjdb** [comment]
This is in essence a breaking change as we had LOGUNIF(ORM) as default for _at least_ the permeability but maybe also for things like the fault transmiscibility multiplier and maybe others?

I'm fine with the breaking change **but** we might need to update the Norne testdata file such that we still use what was intended.

**Comment by olelod** [comment]
The Norne testdata file is updated such that the parameters that had `loguniform: true` now have `distribution: logunif`. But permeability may have been set to loguniform inside the code (not in the config). Ill take a look at this ASAP.
