### ISSUE TITLE
Example of YAML configuration file

### ISSUE THREAD

**Issue by PeliRiccardo** [equinor/flownet#299]
Dear developers,

I am trying to use flownet, but I don't find any YAML configuration file example.
I'm looking to the documention, but it is no present even in the Egg model example, which seems to be complete but lacks such a file.
Could you please provide a complete example?

Thank you!
Riccardo

**Comment by olelod** [comment]
Hi Riccardo,

You can find test data in a separate repository: https://github.com/equinor/flownet-testdata

**Comment by Riccardopeli** [comment]
Thank you.
I still have troubles in launching an example. 
In particular, from the folder `flownet-testdata-master/norne`, I run

`flownet ahm ./config/assisted_history_matching.yml ./output/`

and I get:
```
Traceback (most recent call last):
  File "/home/riccardo/.local/bin/flownet", line 8, in <module>
    sys.exit(main())
  File "/home/riccardo/.local/lib/python3.6/site-packages/flownet/_command_line.py", line 274, in main
    args.func(args)
  File "/home/riccardo/.local/lib/python3.6/site-packages/flownet/_command_line.py", line 68, in flownet_ahm
    config = parse_config(args.config, args.update_config)
  File "/home/riccardo/.local/lib/python3.6/site-packages/flownet/config_parser/_config_parser.py", line 1085, in parse_config
    + ", ".join([error.msg for error in suite.errors])
ValueError: The configuration is not valid:Unknown key: distribution, Unknown key: distribution, Unknown key: distribution
```

Am I missing anything? The arguments seem correct to me. I tried the three examples with the same outcome.

Thank you,
Riccardo

**Comment by olelod** [comment]
@Riccardopeli 

I think it should be fixed by pulling the master branch of FlowNet again, and do `pip install -e .` as before. I think distrubitons may have been added to the config file after you first installed FlowNet.

**Comment by Riccardopeli** [comment]
Thank you, that solved the issue.
