### ISSUE TITLE
Infilling wells

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#311]
I'm trying to include infilling wells in the Flownet network. 
Thus, I included producer wells which are **SHUT** in the history matching period and are **OPEN** in the prediction schedule.
Besides performance of such an approach, I noticed that even the wells that are **SHUT** are history matched (the production rate is 0 but the BHP is matched).

Is there a way to force Flownet to ignore these wells during the history matching phase?
Is this approach the correct one to include infill wells in the network?
Thank you

**Comment by wouterjdb** [comment]
I think that FlowNet, in its current state, will not perform well for infill wells. That is, you can simulate them but you will (should!) get a very large spread in predictions as without proper conditioning you are unlikely to get much predictive power. The what and how, wrt this conditioning is still an open research question. Please let us know if you have some good ideas.

If you would add an infill well in your original simulation model in the prediction time (and simulate it as well) the well should end up in the FlowNet model. If you then create a FlowNet model where you limit the training time to only include the historic period you should end up with a situation where you have the well include in the FlowNet model but it will only start flowing in the prediction period. If this results in the well's BHP being matched you have found a bug 🐛 .

**Comment by Riccardopeli** [comment]
Thank you for the answer. I let you know if I get some good results
