### ISSUE TITLE
Remove "unused" connections in wells

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#314]
In the Norne model it ws observed that in many wells some connections are only defined at the time of drilling for PLT/RFT matching purposes - but are never produced afterwards. This leads to many unwanted connections in FlowNet.

We could try to ignore these connections automatically to improve performance.

@edubarrosTNO is performing a manual check in Norne to see the impact of removing the unneeded connections.

**Comment by edubarrosTNO** [comment]
Closed by https://github.com/equinor/flownet-testdata/pull/36
