### ISSUE TITLE
Network visualization

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#319]
Is there a way to visualize the Flownet network through ResInsight?
In particular, the connection parameters

**Comment by wouterjdb** [comment]
You can visualize the FlowNet using ResInsight. The parameters themselves you cannot visualize directly. You can however create (in 3D) statistical properties (like PORO, PERM) to visualize things like the P10/mean/P90 values.

It would be highly valuable if we could have a better way of visualizing the variables. Want to contribute?
