### ISSUE TITLE
hisotry match keywords

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#320]
I have some questions about history matching in Flownet:

1. Are the parameters independetly sampled from prior distributions? Or there is a dependence by default?
2. Is localization present in the history matching algorithm? Is there a keyword for localization in the configuration file?
3. What is the role of the keyword **hyperopt** in the flownet section in the configuration file?

Thank you

**Comment by wouterjdb** [comment]
1. Yes, independent.
2. There is localization functionality build into ERT. I think one can modify this by using the [ERT API](https://github.com/equinor/ert/blob/9fa2d34a0b76505cf0384f9844408d4cee794d05/docs/rst/manual/advanced/api.rst).
3. It was used to do brute force optimization at one point - but that didn't work out very well. It should probably be removed. Hyperopt has recently been used again though for making it possible to run "hyper parameter optimization" on your configuration file. Results are then stored in MLFlow for analysis. See [this](https://github.com/equinor/flownet-testdata/blob/master/egg/config/hyperparameter.yml) file for an example of the usage.
