### ISSUE TITLE
Analytics returns only iterations between 0 and 9

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#323]
If one performs more iterations you will get the 9th iteration repeated over and over.

I think this is the line to blame:

https://github.com/equinor/flownet/blob/0aeebe0ff7cdce86fb8c4cff8caecabee939c8ec/src/flownet/ahm/_ahm_iteration_analytics.py#L293

The regular expression seems OK, I think it is the sorting that causes this:

9th iteration

`0,1,2,3,4,5,6,7,8,9 --> 9`

10th iteration

`0,1,10,2,3,4,5,6,7,8,9 --> 9`

etc...

**Comment by LonnekevB** [comment]
Check if this is the case: #310 when writing tests
