### ISSUE TITLE
Incorrect writing of RSVD tables

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#326]
This is probably related to the changes from https://github.com/equinor/flownet/pull/322. There is a bug when writing the RSVD table. Different behavior when using `norne_static/rsvd.csv` and `norne_static/rsvd_multiple.csv`, but in both cases the table is written wrongly in `SOLUTION_PARAMETERS.inc`. When I reviewed and tested PR last week, I did not observe this behavior, but there were more commits after that.

**Comment by edubarrosTNO** [comment]
When providing a single RSVD table (i.e. `rsvd.csv`), we see a problem with a line-header of the table that should commented out (i.e., preceded by `--`):
```
RSVD
depth rs
2582.0 120.25
2597.0 110.00
2660.7 106.77
2697.9 106.77
/
depth rs
2582.0 120.25
2597.0 110.00
2660.7 106.77
2697.9 106.77
/
```

**Comment by edubarrosTNO** [comment]
And, when providing multiple RSVD tables (i.e. `rsvd_multiple.csv`), we see a problem with a line-header of the table that should commented out (i.e., preceded by `--`) and a problem with the written contents of the table (I think the wrong columns of the dataframe is being used, plus I think multiple tables are being written at a single entry of the RSVD keyword, i.e. there should be a single table for each `/`):
```
RSVD
rs eqlnum
120.25 1
110.00 1
106.77 1
106.77 1
94.5000 2
94.3 2
94.1 2
120.25 3
110.00 3
106.77 3
106.77 3
94.5000 4
94.3 4
94.1 4
120.29 5
110.00 5
106.77 5
106.77 5
/
rs eqlnum
120.25 1
110.00 1
106.77 1
106.77 1
94.5000 2
94.3 2
94.1 2
120.25 3
110.00 3
106.77 3
106.77 3
94.5000 4
94.3 4
94.1 4
120.29 5
110.00 5
106.77 5
106.77 5
/
(...)
```

**Comment by olelod** [comment]
You checked the files when running locally? Have you pull the latest master when installing FlowNet? This is what the relevant part of SOLUTION_PARAMETERS.inc look like on my VM when running on the master of FlowNet and the master of FlowNet testdata:

![rsvd_multiple](https://user-images.githubusercontent.com/46521401/107776824-5d913a80-6d42-11eb-80e7-fc97b431aa7f.JPG)
![rsvd](https://user-images.githubusercontent.com/46521401/107776829-5ff39480-6d42-11eb-9243-3ec386366cf3.JPG)

**Comment by wouterjdb** [comment]
I just looked at the template for the RSVD table and the colum names are not outputted at all:

```jinja2
RSVD
{% for i in range(nr_eqlnum) -%}
{%- for _, row in rsvd.iterrows() -%}
{{ row['depth'] }} {{ row['rs'] }}
{% endfor %}/
{% endfor %}
```

Which is in line with what @olelod is saying. It therefore seems like you are not using the latest version @edubarrosTNO.

Could you please check and see if we can close this issue then.

**Comment by edubarrosTNO** [comment]
sorry, my bad! I had pulled the latest version, but the installation on my virtual environment needed some refreshing. In any case, false alarm! Issue closed.
