### ISSUE TITLE
Problems with layering option for Norne after removing unused well connections

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#328]
For the modified version of the Norne model where the unused (non-production) well connections are removed from the schedule file (https://github.com/equinor/flownet-testdata/pull/36), the FlowNet model cannot be successfully created when using the `layers` option. The grid seems to be generated but the schedule file cannot be created. The printed error message indicates that one of the wells ends up having no connections associated with it and therefore cannot have any controls prescribed. This occurred when I used `layers: [[1, 4], [5, 22]]`, and it does not occur when the `layers` option is not used.

**Comment by edubarrosTNO** [comment]
As far as I know this issue is not solved yet. PR equinor/flownet-testdata#36 was merged, but that only means that the version of the Norne model without the unused well connections is uploaded. Now FlowNet runs for the Norne model that is in the `flownet-testdata master` when running without the `layers` option, but it still fails when using `layers: [[1, 4], [5, 22]]`. Or did you manage to run it, @wouterjdb or @LonnekevB ?

**Comment by LonnekevB** [comment]
Ok. I thought we had this incorporated in another issue, that's why we removed it. But if it now runs without the layers option and not with the layers than this is relevant again indeed! Will get back at it! 👍

**Comment by LonnekevB** [comment]
Update: Fails on producing the Schedule file because some wells (E-4AH, D-4AH and E-3AH) in the top layer don't have connections. The first two wells are removed by  _remove_long_connections(). Setting max_distance to 1200 should fix these two wells. The thrid well E-3AH is already non-connected before this function is called. Not sure yet why this is. Probably because it is on its own island (although the code says all nodes are connected).

**Comment by wouterjdb** [comment]
![image](https://user-images.githubusercontent.com/9119793/109294196-2a17db00-782d-11eb-9f51-cc25b85bf30b.png)

**Comment by LonnekevB** [comment]
Was D-3AH also a problem then? Hadn't encountered an error for that well yet. Or do you mean E-3AH?

**Comment by wouterjdb** [comment]
Maybe I'm wrong there. I'm only struggling with E-4AH at the moment.

**Comment by edubarrosTNO** [comment]
> Maybe I'm wrong there. I'm only struggling with E-4AH at the moment.

I would be surprised if all connections to E-4AH are removed due to too-long-connections. I say that because there should be injector F-4H that supports E-4AH in the top layer. That well should not be too far. Maybe that connection is triggered as too long because we are using some default values for `max_distance` or `max_distance_fraction` options?
