### ISSUE TITLE
Enable multiple analytics workflow in history matching mode

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#330]
In order to derive error estimates to objectively assess the quality of FlowNet simulations in prediction mode (i.e. when running `flownet pred ...`), the existing analysis option must be extended to the prediction mode. This implies parsing this option in the prediction configuration file and enabling the ERT workflow job in the generated ERT setup for the prediction runs.

This task will require that the "truth" reference simulation model is also run for the prediction period, so that there is a reference to compute the errors of the FlowNet ensemble. This could be handled by making sure that the reference simulation is run offline for a very long period including the prediction period, but a more elegant and flexible solution would be to make the FlowNet scripts launch the reference simulation for the prediction period too (which would allow the quality of FlowNet simulations to be assessed for different prediction schedules).

**Comment by wouterjdb** [comment]
2 times in history
1 in pred

blue+green+purple

![image](https://user-images.githubusercontent.com/9119793/108481123-118d4b00-7298-11eb-964a-2839cefb895e.png)
