### ISSUE TITLE
Time shift in FlowNet results compared to original case

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#36]
Original author: @wouterjdb 

![image](https://user-images.githubusercontent.com/9119793/74417844-b5ebde80-4e47-11ea-891d-165f32deef2a.png)

Is this an issue?

**Comment by olwijn** [comment]
There is an error in all FLOWNET times appearing in the SCHEDULE section, and also the START time is wrong. While the ECLIPSE times are all the first day of the month, FLOWNET assigns the last day of that month.

**Comment by olwijn** [comment]
All information to reconstruct the correct start and report dates is available in the output of EclSum (EclipseData class): start_date and report_dates. Only the production data contained in this output are stored in the dataframe that is subsequently used (https://github.com/equinor/flownet/blob/master/src/flownet/ahm/_run_ahm.py:154).

**Comment by olwijn** [comment]
There is a problem with the resampling/interpolation done on the dataframe entries (https://github.com/equinor/flownet/tree/master/src/flownet/data/from_eclipse.py:145). It results in dates that do no longer correspond to the report dates.

**Comment by olwijn** [comment]
Two other kinds of errors occur : (1) averaging of multiple values within the same month, (2) assigning a singe value to another date in that month. 

(1) If there are multiple values, we probaly want to use the first one only (assuming it corresponds to a report time at the frist day of the month). 
(2) If there is only one value, we want to use the date corresponding to that value.

Another way to approach this is to consider the actual report dates from the schedule instead of relying on the simulator times.

**Comment by anders-kiaer** [comment]
Nice! `M` vs `MS` is a good catch. There are two options: Either we always in the code transfers `M` to `MS` before giving it to `pandas`, or we keep the user in control of what is given (without any extra logic).

I'm leaning towards the latter, and simply change the example configuration files from using `x` to `xS`.

Do you want to make a ~two-line PR of your findings @olwijn and then I would say we can close this issue :tada: :champagne:

**Comment by olwijn** [comment]
Will do. One final note: if there are large intervals between reporting dates in the schedule (for example, after 2003 in the Brugge schedule only the 1st day of each year is a reporting date), the simulator may take steps do not correspond with, for example, the first day of a month. Currently we interpolate all these values to the first day of the month (if one uses MS) by default. It would in general be preferable to use the actual dates at which measurements are reported and avoid any interpolation. Also, one may want to downsample the measurement time series if the measurement frequency is very high. For exaple: select only the first measurement in each calendar month. I have not yet encountered an easy option to do this.

**Comment by olwijn** [comment]
After running Flownet with the new changes I noticed one more issue with the 
![image](https://user-images.githubusercontent.com/13539085/81280614-06df2d80-9059-11ea-8f47-1586c1c51230.png)
![image](https://user-images.githubusercontent.com/13539085/81280665-1c545780-9059-11ea-8e49-d4f4a295e79b.png)

**Comment by olwijn** [comment]
One final note: if there are large intervals between reporting dates in the schedule (for example, after 2003 in the Brugge schedule only the 1st day of each year is a reporting date), the simulator may take steps do not correspond with, for example, the first day of a month. Currently we interpolate all these values to the first day of the month (if one uses MS) by default. It would in general be preferable to use the actual dates at which measurements are reported and avoid any interpolation. Also, one may want to downsample the measurement time series if the measurement frequency is very high. For exaple: select only the first measurement in each calendar month. I have not yet encountered an easy option to do this.

**Comment by olwijn** [comment]
A note on resampling: if there are large intervals between reporting dates in the schedule (for example, after 2003 in the Brugge schedule only the 1st day of each year is a reporting date), the simulator may take steps that do not correspond with, for example, the first day of a month. Currently we interpolate all these values to the first day of the month (if one uses MS) by default. It would in general be preferable to use the actual dates at which measurements are reported and avoid any interpolation. Also, one may want to downsample the measurement time series if the measurement frequency is very high. For exaple: select only the first measurement in each calendar month. I have not yet encountered an easy option to do this with the panda functionality.

**Comment by olwijn** [comment]
There is still something strange happening in the dataframe interpolation:
![image](https://user-images.githubusercontent.com/13539085/81319234-a8817180-908f-11ea-8012-be28b53c1829.png)

**Comment by olwijn** [comment]
A note on resampling: if there are large intervals between reporting dates in the schedule (for example, after 2003 in the Brugge schedule only the 1st day of each year is a reporting date), the simulator may take steps that do not correspond with, for example, the first day of a month. Currently we interpolate all these values to the first day of the month (if one uses MS) by default. It would in general be preferable to use the actual dates at which measurements are reported and avoid any interpolation. Also, one may want to downsample the measurement time series if the measurement frequency is very high. For exaple: select only the first measurement in each calendar month. I have not yet encountered an easy option to do this with the panda functionality.

**Comment by olwijn** [comment]
The theoretically correct way to deal with the times (if they are extracted from an ECLIPSE run at least), is as follows. (1) Remove all resampling/interpolation and work directly with the ECLIPSE dates. (2) Assign values that are used as well targets for Flownet to the simulation step immediately preceding the date at which they are reported by ECLIPSE. So the values that are used as observations need to remain at the ECLIPSE dates. This requires that: (1) The dates preceding the first non-zero value for each well has to be retained in the pandas dataframe. This needs to be done in _production data in from_eclipse.py (this has been done already). (2) The WCONHIST and WCONINJH keyword entries have to be modified based on the chosen control mode. It is not quite clear yet what the best way is to do this.
