### ISSUE TITLE
WWIR quantity ignored in the analysis?

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#390]
I am running the Flownet ahm on the Egg model in equinor/flownet-testdata, with the attached configuration file.

[assisted_history_matching.yml.txt](https://github.com/equinor/flownet/files/6397696/assisted_history_matching.yml.txt)

I added the quantity WWIR in the analysis, but it seems to be ignored and not included in the analysis. I see this looking at the history matching output through webviz and it is not present even in the `observations_training.yamlobs` file.

![webviz](https://user-images.githubusercontent.com/18396660/116542321-d426e880-a8ec-11eb-8293-ec9bd776e0d5.png)
[observations_training.yamlobs.txt](https://github.com/equinor/flownet/files/6398110/observations_training.yamlobs.txt)

Is it a bug or am I doing anything wrong?

P.S. I know that matching WWIR imposing the injection rate does not make any sense, but it is the same running the injectors in the BHP control_mode

**Comment by olelod** [comment]
The WWIR (or WGIR) was not written correctly to the yamlobs-file. It is written to the ertobs-file, so it is used by ERT in the conditioning, but not included in the visualization of the results.
