### ISSUE TITLE
Need to provide two-way THPRES values

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#399]
Currently in FlowNet THPRES values between two adjacent flow tubes are defined only in one direction.
For example:
```
THPRES
787 793 1* /
422 143 1* /
773 895 1* /
768 551 1* /
(...)
```
Is the two-way effect taken into account by default in OPM-Flow? Is it necessary to enable any options in the RUNSPEC section to activate that? Do we need to explicitly add the two-way values in the THPRES keyword? This seems to be the case in the Norne reference simulation case where THPRES is defined both ways with non-defaulted values even though the values are identical, see below.
```
THPRES
  1 2 0.588031 /
  2 1 0.588031 /
  1 3 0.787619 /
  3 1 0.787619 /
  1 4 7.00083  /
  4 1 7.00083  /
/
```

**Comment by edubarrosTNO** [comment]
As a test, I have looked into a realization of the FlowNet model (randomly selected from the posterior ensemble of a recent HM experiment) and simulated it **with** and **without** the THPRES keyword in the SOLUTION_PARAMETERS.inc. After a brief inspection of various field and well simulated data, there seem to be no differences between the two simulations. Maybe OPM-Flow is calculating zero THPRES values based on initial conditions and that is why this is making no difference

**Comment by edubarrosTNO** [comment]
I have also run the Norne reference simulation with and without the THPRES keyword as described above. And again there were no differences between the simulations in terms of simulated field / well production

**Comment by edubarrosTNO** [comment]
A further look into the FlowNet simulation model described above. The EQLNUM entries in the THPRES keyword indicate a rather large number of EQLNUM (i.e. we see numbers like 787, 793, 422, ...). However, the RUNSPEC section of this model has the EQLDIMS keyword defining 5 regions (= consistent with Norne reference model). In the SOLUTION section the EQUIL keyword also has 5 entries for each of the 5 regions.
@wouterjdb, are you sure that each flow tube has its own equilibration region?

**Comment by wouterjdb** [comment]
No, it has not.

**Comment by edubarrosTNO** [comment]
> No, it has not. You can define that if you want to though. But we are not doing that in our recent (months...) runs.

Then why in the FlowNet model we have
```
THPRES
-- EQLNUM  EQLNUM  VALUE
    787     793      1*  /
    422     143      1*  /
    773     895      1*  /
    768     551      1*  /
    (...)
```
?

**Comment by wouterjdb** [comment]
https://github.com/equinor/flownet/blob/c66e97e8c67155696802a8380c0e51c1bd3eaab6/src/flownet/parameters/_equilibration.py#L110-L125

Because this code has not been updated. This seems to implicitly assumes that if `if len(self._unique_eqlnums) > 1` each tube is an equil region --> 🐛 .
