### ISSUE TITLE
Build script issues on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#4]
The following issues were identified when doing a fresh install of FlowNet on an Ubuntu 18.04 LTS machine:

- **The installation stops and informs the user that Python3 venv needs to be installed**:
```
Building a virtual environment at /home/media-unix/flownet/venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/media-unix/flownet/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```
Running the suggested command, with sudo, solves the issue.

- **When running a test AHM case FlowNet stops when ERT is launched**, with the following error:
`ImportError: Failed to import any qt binding`
This requires that PyQt5 is installed. However, if one runs `pip install PyQt5` the following error is returned:
```
(venv) media-unix@media-unix:~/flownet/examples$ pip install PyQt5
Collecting PyQt5
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 248kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-xmx1z3c3/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xmx1z3c3/PyQt5/
```
This can be solved by installing a different version, for example, `pip install pyqt5==5.14.0` works fine.

After fixing those two issues, FlowNet ran fine.

**Comment by anders-kiaer** [comment]
> When running a test AHM case FlowNet stops when ERT is launched
`pyqt5` should not be needed when running the `ert cli` only. Is this seen also when using latest `ert`?

**Comment by anders-kiaer** [comment]
Regarding `apt-get install python3-venv`, I guess it can be discussed if this should be a prerequisite, or part of the `flownet` `venv` build script (e.g. we already assume that Python3 is installed).

**Comment by anders-kiaer** [comment]
I think we can treat this one as closed (feel free to reopen @wouterjdb if you want).
- We are currently running CI on an Ubuntu machine.
- The `PyQT5` dependency of `ert` should not be necessary when using `cli` (if it is, it is an `ert` issue).

I also see that both `libecl` and [`libres`](https://pypi.org/project/equinor-libres/) are now on PyPI - so the build script can probably soon be simplified a lot.
