### ISSUE TITLE
Assign THPRES values per region of the reference model

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#400]
Currently in FlowNet models THPRES values are assigned between each of the adjacent tubes assumed to have each their own equilibration region (EQLNUM). The EQUIL keyword is used based on the equilibration regions of the reference model. Would it be useful to assign THPRES values according to regions of the reference model as well? Could this help improve results?

For example, in the Norne case, the reference model has:
```
-- EQLNUM EQLNUM THPRES
-- FROM TO VALUE
THPRES
  1 2 0.588031 /
  2 1 0.588031 /
  1 3 0.787619 /
  3 1 0.787619 /
  1 4 7.00083  /
  4 1 7.00083  /
/
```

**Comment by wouterjdb** [comment]
See #399 for discussion around this.
