### ISSUE TITLE
Specifying rel_error and min_error in the config yaml

### ISSUE THREAD

**Issue by olelod** [equinor/flownet#409]
Currently the `flownet->data_source->simulation->input_case->vectors->XXXX` has AllowNone for `rel_error `and `min_error`. Both of them are required for generation of the `.yamlobs` and `.ertobs` file. No warnings or errors are issued if one of `rel_error `and `min_error` is not specified, the observations for that vector is just dropped. If both are missing one get a `not-a-dictionary` error.

**Comment by plgbrts** [comment]
What would be the best?
A: if not both (rel_error & min_error) are given,  a warning should be provided  with a message that the associated observation is dropped
or
B: if not both (rel_error & min_error) are given,  an  error should be given that the error specification is incomplete.

I assume B would be prefered  but like to have a confirmation

**Comment by olelod** [comment]
I agree. B would be the preferred option (at this point, at least).
