### ISSUE TITLE
Incorrect removal of aquifer NNC's?

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#5]
In the "global" aquifer scheme, aquifer nodes visually lie on top of one another but were for some historical reason not connected with NNC's. The code below is responsible for that, but seems to also remove NNC's for aquifers in the "individual" scheme:

https://github.com/equinor/flownet/blob/e73fd20f1c7ba90cbb6be58e727842b6f06962a1/src/flownet/network_model/_network_model.py#L145-L151

Could this  potentially lead to aquifers that are not directly connected to a well to not be connected to the grid at all?

**Comment by edubarrosTNO** [comment]
I have taken a closer look at this issue. To do so, I used the Egg model FlowNet example and enabled aquifer nodes to all nodes (i.e. well and additional nodes). And I verified that aquifer nodes were connected to both well nodes and additional nodes when using both the "global" and the "individual" aquifer schemes, i.e. the top grid cells of the aquifer "flow tubes" were all listed in the NNC keyword connecting them to grid cells of other "flow tubes". This issue can be closed!
