### ISSUE TITLE
Well status showing as 'STOP' in schedule file

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#57]
This refers to the latest changes from PR #56 by @anders-kiaer and @olwijn .

I saw all the checks and reviewer's approval ✅ and took the liberty to merge the PR, because I wanted to try this fix as soon as possible. But there seems to be a bug: the wells are all showing `'STOP'` status in the history schedule (both producers and injectors). See below for the Brugge case:
```
WCONHIST
-- WELL OPEN/ CNTL OIL  WAT  GAS  VFP   VFP  THP  BHP
-- NAME SHUT  MODE RATE RATE RATE TABLE ALFQ PRES PRES
  'BR-P-1' 'STOP' 'RESV' 317.9749 0.0051 0 1* 1* 63.7635 69.8381 /
  (...)
/
WCONINJH
-- WELL FLUID OPEN/ SURF RESV BHP  THP  VFP   NOT  CNTL
-- NAME TYPE  SHUT  RATE RATE PRES PRES TABLE USED MODE
  'BR-I-1' 'WATER' 'STOP' 635.9500 150.8748 0 1* 1* /
  (...)
/
```

**Comment by edubarrosTNO** [comment]
I did some research here, and here is what I thought about:
1. Are we sure that `WSTAT` information is output in the summary file of Eclipse / OPM-Flow? I found no reference to it in the OPM-Flow documentation manual. In the log-file of the OPM-Flow simulation it is printed that `Summary keyword 'WSTAT' is unhandled`.
2. In the Eclipse manual I found that `WSTAT, Well State Indicator: The output is rendered as mnemonics in the .RSM file`.
3. As far as I know, the `.RSM` file is not yet supported by OPM-Flow. And even if it is, I do not think that `libecl` can read `.RSM` files. I guess we would have to write separate scripts for that.
4. Of course, we could try to think of an alternative way of extracting dynamic information about the `OPEN/SHUT` status of the wells.

**Comment by anders-kiaer** [comment]
Writing `WSTAT` output is not supported by OPM Flow (yet), but Eclipse supports it. So currently the Eclipse input case to FlowNet needs to be simulated with Eclipse (and with `WSTAT` in `SUMMARY` section). Then you get standard summary vectors of the format `WSTAT:WELLNAME` with integer values.

FlowNet itself of course still can use Flow (as `WSTAT` is only needed when reading/parsing the initial input case).

Can you verify that your Eclipse input case has `WSTAT:*` vectors in its `UNSMRY`?

**Comment by olwijn** [comment]
I have re-run the Brugge case with WSTAT exported. I will share it with you.

**Comment by edubarrosTNO** [comment]
Thanks, it seems to work now. It's a pity that it needs to be re-run in Eclipse because we don't have Eclipse in our VM's.
I will close this issue for now. We keep working towards the Brugge predictions
