### ISSUE TITLE
Use posterior ensemble mean for new prior

### ISSUE THREAD

**Issue by olwijn** [equinor/flownet#66]
Practical experience shows that history matching results may still contain biases. A two-step solution approach was proposed by Guo and Reynolds (2019) to address this, in which the posterior ensemble means are used as the means for a new prior in a second application of the history matching workflow.

If the ensemble of parameter estimates is saved in a compact form at the end of the history matching, new functionality could be introduced to specify that the mean of the new prior should be taken from this file.

**Comment by anders-kiaer** [comment]
The posterior parameters from an AHM run is automatically stored, and is already being used in prediction runs:

https://github.com/equinor/flownet/blob/6447c6dd219d3da6ac8a84fb8f10a3c4b6dd640d/src/flownet/prediction/_run_pred.py#L53-L54

The same file could probably be used when solving this task.

**Comment by olwijn** [comment]
All prior parameter distributions are currently defined by min and max (or one of these and a mean) and a boolean indicating if the distribution is loguniform or not. These distributions are save in a pickle file. It looks like actual values are sampled by ERT and that updated values are written to a parquet file.

**Comment by olwijn** [comment]
It is possible (in principle) to loop over all entries of the parameters list created in the example above and update the min or max values of the distribution based on the updated ensemble means that are read from the values in the parquet file. Direct modification of the distribution values is not possible however (they appear to be protected somehow).

**Comment by olwijn** [comment]
A new entry was added to the config file under model_parameters (ahm_case) that specifies the path to a previous HM experiment. For example:
model_parameters:
   ahm_case: ../../examples/ahm_norne_out
   permeability:
(etc.)
The file parameters_iteration-latest.parquet.gzip should be located in ahm_case. The ensemble-mean parameter values are computed and used to find a new extreme value for a uniform or loguniform distribution through optimization (the maximum value from the prior distribution is kept fixed if the mean has moved towards the minimum and vice versa).
