### ISSUE TITLE
wells status  by default

### ISSUE THREAD

**Issue by tayloris** [equinor/flownet#69]
Flownet set wells status "CLOSED" by default.  I'm applying flownet for the egg model and all wells are set to be "CLOSED" by default. Maybe, flownets should warn the user when wells status is not defined in the original model.

**Comment by tayloris** [comment]
I understand now what Anders said about having "WSTAT" in the summary anyhow, I can add a warning there specifying that the default value will be imposed. So we want "CLOSED" as the default?

**Comment by anders-kiaer** [comment]
Maybe we should simply throw a `RuntimeError` in FlowNet if `WSTAT` is not in the input model (since we basically depend on it existing)?

**Comment by tayloris** [comment]
I agreed,

**Comment by tayloris** [comment]
I'm able now to determine if there any  WSTAT = NaN by asking        
  ```
 if df_production_data["WSTAT"].isna().any():
            raise RuntimeError(f"The status of each well must be define (OPEN, SHUT, STOP). Please add keyword WSTAT in the SUMMARY section of eclipse case.")
        else:
            df_production_data["WSTAT"] = df_production_data["WSTAT"].map(
                {
                    1: "OPEN",  # Producer OPEN
                    2: "OPEN",  # Injector OPEN
                    3: "SHUT",
                    4: "STOP",
                    5: "SHUT",  # PSHUT
                    6: "STOP",  # PSTOP
                    np.nan: "STOP",
                }
            )
```
However, I add WSTAT inside the summary section of my eclipse file and flownet  doesn't add the corresponding well status WSTAT :(

**Comment by tayloris** [comment]
Where do I add WSTAT on my eclipse file?

**Comment by anders-kiaer** [comment]
Adding `WSTAT` in `SUMMARY` should be enough, however, Flow does not support it as of today so the input case has to be run with Eclipse. Could that be the reason?

**Comment by tayloris** [comment]
Yes that's the reason then

**Comment by wouterjdb** [comment]
I now ran into the same problem with Norne it looks like.
